version: '3.8'

services:

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    # add volume for persistence 
    volumes:
      - redis_cache:/data

volumes:
  redis_cache:

networks:
  backend:
